Kaatje/app/add cosplay
FriendsCodeTogether/cosnet pull request #22
Opened 2020-10-19 10:14 UTC by kaiye13

made with rube without database

2020-10-19 12:07 UTC, timblokken requested changes
- [x] datum velden moeten datepickers zijn

- [x] consistency in naamgeving van elementen

- [ ] valuta voor budget, op zijn minst decimaal met 2 getallen en euro teken

- [x] default values zoals aangeven op wireframes

- [ ] view aanpassen

- [x] placeholders in velden

- [x] juiste lettertypes

- [x] gradient toevoegen

- [x] png moeten svg zijn (voor schaalbaarheid)

2020-10-21 14:35 UTC, timblokken approved these changes

2020-10-21 14:43 UTC, Kenny-Lacroix approved these changes

2020-10-21 14:45 UTC, Kenny-Lacroix approved these changes

2020-10-21 14:45 UTC, Joren-Thijs approved these changes
![afbeelding](https://user-images.githubusercontent.com/41837971/96736362-d3048400-13bc-11eb-89f1-f974c43b61eb.png)

2020-10-21 14:51 UTC, merged